### ISSUE TITLE
Wear OS

### ISSUE THREAD

**Issue by Isaksson** [stefan-torstensson/openhab-remote#24]
Hello.
Thanks for this great application.
I have a question, any chance that you will port this to Wear OS 3.0?

**Comment by stefan-torstensson** [comment]
No, that would essentially require a complete re-write using the Wear OS SDK and I don't have enough spare time for such an endeavour. Even though Samsung has claimed at times that Wear OS 3 was a merge of Tizen and Wear OS there's no support for Tizen applications.

**Comment by Isaksson** [comment]
Thanks for the information.
My hope was that you had plans to change your watch to an new Samsung with Wear OS and that you already had started the work with the app.
Anyway, thanks for the work with this app 👍
